
source('D:/R/R-2.13.2/library/FLSAM-master/R/af.R')
source('D:/R/R-2.13.2/library/FLSAM-master/R/an.R')
source('D:/R/R-2.13.2/library/FLSAM-master/R/anf.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/FLSAM.control.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/FLSAM.r')

source('D:/R/R-2.13.2/library/FLSAM-master/R/createAccessors.R')
source('D:/R/R-2.13.2/library/FLSAM-master/R/diagnostics.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/diags.R')
source('D:/R/R-2.13.2/library/FLSAM-master/R/FLR2SAM.r')

source('D:/R/R-2.13.2/library/FLSAM-master/R/FLSAM.out.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/kobe-FLSAM.R')
source('D:/R/R-2.13.2/library/FLSAM-master/R/looi_retro.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/methods.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/methods_plots.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/monteCarloStock.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/pin.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/SAM2FLR.r')
source('D:/R/R-2.13.2/library/FLSAM-master/R/zzz.R')