---
output: 
  word_document:
    reference_docx: ../report_template_v1.5.dotx
---

```{r setup, include=FALSE}

# =======================================================================================
# WGWIDE Stock summaries.Rmd
# 
# Generate stock summary report for WGWIDE
#
# 03/09/2017 first version
# 06/08/2018 UPdated and prepared for WGWIDE 2018
# 07/09/2018 Added link to SAG database for plotting. Currently reading from downloaded data. 
#            Needs to be made through live connection. 
# =======================================================================================

require("knitr")
knitr::opts_chunk$set(echo = FALSE,	message = FALSE,	warning = FALSE,	comment = "",	crop = TRUE )
knitr::opts_chunk$set(fig.width=10) 

rm(list=ls())

# library(devtools)
library(icesDatras)   # install.packages("icesDatras")
library(tidyices)     # devtools::install_github("fishvice/tidyices", dependencies = TRUE)
library(tidyverse)    # tidying packages
library(readxl)       # read excel
library(lubridate)
library(sf)
library(sp)
library(data.table)
library(scales)
library(RColorBrewer)

# library(gisland)      # devtools::install_github("einarhjorleifsson/gisland", dependencies = TRUE)

library(maps)
library(mapdata)
library(mapproj)
library(lubridate)
library(viridis)

library(animation)
library(gganimate)

# source my utils
source("D:/GIT/mptools/R/my_utils.r")

# Data path
datapath <- "D:/WGWIDE/2018/06. Data/_catch_by_rectangle"

# iadvice path
iadvicepath <- paste(get_dropbox(), "/iAdvice", sep="")

# set onedrive directory
onedrive <- file.path(Sys.getenv('USERPROFILE'), 'PFA/PFA team site - PRF') 

# load spatial datasets
load(file.path(onedrive, "rdata/world.df.RData"))
load(file.path(onedrive, "rdata/eez.df.RData"))
load(file.path(onedrive, "rdata/fao.df.RData"))
load(file.path(onedrive, "rdata/depth200.df.RData"))
load(file.path(onedrive, "rdata/icesrectangles.df.RData"))

load(file.path(onedrive, "rdata/fao.RData"))
load(file.path(onedrive, "rdata/afsis.RData"))

# load HOM data
load(file.path(datapath, "CatchBySR HOM.RData"))

# load the stock data
iAssess <- 
  get(load(file=paste(iadvicepath, "/rdata/iAssess.RData",sep=""))) %>% 
  filter( (stockkeylabel == "mac.27.nea" & assessmentyear == 2018 & purpose == "advice") |
          (stockkeylabel == "hom.27.2a4a5b6a7a-ce-k8" & assessmentyear == 2018 & purpose == "advice") |
          (stockkeylabel == "whb.27.1-91214" & assessmentyear == 2018 & purpose == "advice") |
          (stockkeylabel == "her.27.1-24a514a" & assessmentyear == 2018 & purpose == "advice") ) %>% 
  mutate(species = toupper(substr(stockkeylabel,1,3)))  %>% 
  dplyr::select(species, year, stocksize) %>% 
  mutate(stocksize = as.integer(stocksize / 1000))

# catch data by year and country
catch_by_species_year_country <- 
  read_excel(file.path(datapath, "WGWIDE catchesbyrect all.xlsx"), 
             col_names=TRUE, col_types="text") %>% 
  lowcase() %>% 
  mutate_at(c("year","pnum"), list(as.integer) )  %>% 
  mutate_at(c("lat","lon","catch"), list(as.numeric) )  %>%
  
  bind_rows(hom) %>% 
  
  filter(lat > 34) %>% 
  # filter(!(country %in% c("ALL")) )  %>%  
  group_by(species, year, country, icesrect, lat, lon) %>% 
  summarize(catch = sum(catch, na.rm=TRUE)) %>% 
  
  mutate(catch_interval = cut(as.integer(catch), breaks=c(1 %o% 10^(0:12)), dig.lab=10 ) ) %>% 
  mutate(catch_interval = gsub(" ","", catch_interval)) %>% 
  filter(!is.na(catch_interval)) %>% 
  filter(grepl("\\,", catch_interval)) %>%   
  group_by(species, year, country, icesrect, lat, lon, catch_interval) %>% 
  summarize(catch = sum(catch, na.rm=TRUE))

# catch by year
catch_by_species_year <- 
  catch_by_species_year_country %>% 
  group_by(species, year, icesrect, lat, lon) %>% 
  summarize(catch = sum(catch, na.rm=TRUE)) %>% 
  
  mutate(catch_interval = cut(as.integer(catch), breaks=c(1 %o% 10^(0:12)), dig.lab=10 ) ) %>% 
  mutate(catch_interval = gsub(" ","", catch_interval)) %>% 
  filter(!is.na(catch_interval)) %>% 
  filter(grepl("\\,", catch_interval)) %>%   
  group_by(species, year, icesrect, lat, lon, catch_interval) %>% 
  summarize(catch = sum(catch, na.rm=TRUE))

# read_excel(file.path(datapath, "WGWIDE catchesbyrect all.xlsx"), 
#            col_names=TRUE, col_types="text") %>% 
#   lowcase() %>% 
#   mutate_at(c("year","pnum"), list(as.integer) )  %>% 
#   mutate_at(c("lat","lon","catch"), list(as.numeric) )  %>%
#   group_by(species,year,country) %>% 
#   summarize(catch=sum(catch, na.rm=TRUE)) %>%
#   spread(key=country, value=catch) %>% 
#   View()

# ================================================================================
# FUNCTIONS
# ================================================================================

# myspecies = "MAC"; myyears = 1998:2017
# myspecies = "MAC"; myyears = 1998
# myspecies = "MAC"; myyears = NA
# myspecies = "HOM"; myyears = NA

plot_catch_by_year <- function(myspecies="MAC", myyears=NA) {
  
  catch2 <-
    catch_by_species_year %>% 
    filter(species == myspecies) %>% 
    {if ((length(myyears) == 1) & all(is.na(myyears))) {
      filter(.)
    } else {
      filter(., year %in% myyears)
    }}

xlim <- range(catch2$lon, na.rm=TRUE)
ylim <- range(catch2$lat, na.rm=TRUE)

# catch2 %>% filter(lon == -41) %>% View()
# catch_by_species_year_country %>%  filter(species=="HOM", lon == -41) %>% View()

tc <-
  catch2 %>% 
  group_by(species, year) %>% 
  summarize(catch = sum(catch, na.rm=TRUE)) %>% 
  mutate(catch  = as.integer(catch/1000) ) %>% 
  
  group_by(species) %>% 
  mutate(catch2 = ylim[1] + (catch / max(catch, na.rm=TRUE) * (ylim[2] - ylim[1])) )

ta <-
  iAssess %>% 
  filter(species %in% tc$species, year %in% tc$year)

t <-
  tc %>% 
  left_join(ta, by=c("species","year"))

catch2 %>% 
  ggplot(aes(lon, lat)) + 
  theme_publication() +
  theme(panel.border     = element_rect(colour="black" , size=0.2),
        panel.grid.major = element_blank(),
        strip.background = element_rect(colour="black", size =0.2),
        plot.margin      = unit(c(0,0,0,0),"cm"),
        plot.title       = element_text(vjust=0, size=10),
        axis.text        = element_text(size=6),
        legend.key.width = unit(0.4, "cm"), 
        axis.title       = element_blank()) +
  
  coord_quickmap(xlim=xlim, ylim=ylim) +

  geom_polygon(data=fao.df, aes(long, lat, group=group), fill = NA, size=0.2,
               color="gray80", alpha=0.3) +

  geom_tile(aes(fill = catch_interval, height=0.5, width=1), colour=NA, alpha=1.0) +
  scale_fill_viridis(option = "plasma", direction = -1, discrete=TRUE) +

  geom_polygon(data=world.df, aes(long, lat, group=group), fill = "cornsilk", 
               size=0.1, color="black") +
  
  geom_label(data=t, aes(label=paste0("ssb:",stocksize,", catch:",catch)), 
             x=-Inf, y=Inf, hjust=0, vjust=1, inherit.aes=FALSE) +

  labs(x = NULL, y = NULL, size = "tons") +
  guides(fill = guide_legend(nrow = 1, title="catch (tonnes)")) +
  facet_wrap( ~ year, ncol=4)

} # end of plot_catch_by_year

plot_catch_by_year_and_country <- function() {
  
} # end of plot_catch_by_year_and_country

plot_catch_by_year_animated <- function() {
  
} # end of plot_catch_by_year_animated

```

**Catch by rectangle WGWIDE 2018**

&nbsp;  

Martin Pastoors, `r format(Sys.time(), '%d/%m/%Y')`

&nbsp;  

**Mackerel**

```{r, echo=FALSE, fig.asp=1.4, fig.align="center", message=FALSE, warning=FALSE}

plot_catch_by_year(myspecies="MAC")

```

_Figure 1.10.1: Catch of mackerel, western horse mackerel, blue whiting and Norwegian spring spawning herring_

##### page break

**Horse Mackerel**

```{r, echo=FALSE, fig.asp=1.4, fig.align="center", message=FALSE, warning=FALSE}

plot_catch_by_year(myspecies="HOM")

```


##### page break

**Blue whiting**

```{r, echo=FALSE, fig.asp=1.4, fig.align="center", message=FALSE, warning=FALSE}

plot_catch_by_year(myspecies="WHB")

```


##### page break

**Atlanto-scandian herring**

```{r, echo=FALSE, fig.asp=1.4, fig.align="center", message=FALSE, warning=FALSE}

plot_catch_by_year(myspecies="HER")

```